import {} from 'react'
import './Home.css'

function Home(){
    return(
        <div className='home-container'>
        <h1 className='home-title'>Página Inicial</h1>
            <p className='home-p'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Ultricies integer quis auctor elit sed vulputate mi sit amet. Risus nullam eget felis eget. Diam donec adipiscing tristique risus nec feugiat in fermentum. Et tortor consequat id porta. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Facilisi morbi tempus iaculis urna id volutpat. Ornare massa eget egestas purus viverra accumsan in nisl nisi. Vel pretium lectus quam id leo in vitae. Nulla facilisi nullam vehicula ipsum. Ornare aenean euismod elementum nisi quis. Non odio euismod lacinia at quis risus sed vulputate odio. Amet massa vitae tortor condimentum. Tempor nec feugiat nisl pretium fusce id velit ut tortor.

                Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Turpis egestas maecenas pharetra convallis posuere morbi leo urna. Dui ut ornare lectus sit amet est placerat. Quis hendrerit dolor magna eget est lorem ipsum. Et molestie ac feugiat sed lectus vestibulum mattis. Id porta nibh venenatis cras sed. Enim praesent elementum facilisis leo vel fringilla. Ultrices neque ornare aenean euismod elementum. Commodo ullamcorper a lacus vestibulum sed arcu. Sapien et ligula ullamcorper malesuada proin libero. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Felis eget velit aliquet sagittis id consectetur purus ut. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel orci. Ultrices dui sapien eget mi. Sollicitudin ac orci phasellus egestas. Ut faucibus pulvinar elementum integer enim neque volutpat ac. Sagittis aliquam malesuada bibendum arcu vitae. Et netus et malesuada fames ac turpis. In hendrerit gravida rutrum quisque non tellus orci.

                Lorem ipsum dolor sit amet. Massa sapien faucibus et molestie. Ac orci phasellus egestas tellus rutrum. Rhoncus est pellentesque elit ullamcorper dignissim. Vitae suscipit tellus mauris a diam maecenas sed enim. Id diam vel quam elementum pulvinar etiam non quam lacus. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Posuere morbi leo urna molestie at elementum eu facilisis. Lorem ipsum dolor sit amet consectetur. Venenatis cras sed felis eget velit aliquet sagittis id. Nulla aliquet porttitor lacus luctus accumsan tortor. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Tempus urna et pharetra pharetra massa massa ultricies mi quis. Purus gravida quis blandit turpis cursus. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Lorem ipsum dolor sit amet. Vestibulum sed arcu non odio euismod lacinia at quis risus.

                Vel pretium lectus quam id. Quis commodo odio aenean sed. Aenean sed adipiscing diam donec adipiscing tristique risus. Fermentum leo vel orci porta non pulvinar neque. Porta nibh venenatis cras sed felis eget. Velit dignissim sodales ut eu sem. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Integer quis auctor elit sed vulputate mi. Ullamcorper velit sed ullamcorper morbi tincidunt. Sit amet nisl purus in mollis nunc sed id. Bibendum ut tristique et egestas quis ipsum. Diam ut venenatis tellus in. Est sit amet facilisis magna etiam tempor orci eu. Nulla facilisi etiam dignissim diam quis enim lobortis. Tristique senectus et netus et malesuada fames ac turpis egestas.

                Ornare arcu dui vivamus arcu felis bibendum ut. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Elementum integer enim neque volutpat ac tincidunt. In dictum non consectetur a erat nam at lectus urna. Convallis posuere morbi leo urna molestie at elementum. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Neque volutpat ac tincidunt vitae semper quis lectus. Ullamcorper velit sed ullamcorper morbi. In aliquam sem fringilla ut morbi tincidunt augue. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Netus et malesuada fames ac. Nisl purus in mollis nunc sed id semper risus in. Amet nisl suscipit adipiscing bibendum est. Tellus cras adipiscing enim eu turpis egestas. Eget nunc lobortis mattis aliquam faucibus purus in massa tempor.

                Ut sem viverra aliquet eget sit amet. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan tortor. Adipiscing elit pellentesque habitant morbi tristique. Gravida dictum fusce ut placerat orci. Amet mauris commodo quis imperdiet massa tincidunt. Risus viverra adipiscing at in tellus integer feugiat scelerisque. Lectus nulla at volutpat diam ut venenatis. Ultrices neque ornare aenean euismod elementum nisi quis eleifend quam. Sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Amet nulla facilisi morbi tempus iaculis urna id volutpat lacus. Eu tincidunt tortor aliquam nulla facilisi cras fermentum odio. Convallis a cras semper auctor neque vitae tempus. Dictum non consectetur a erat nam at lectus. Purus sit amet luctus venenatis.

                Erat pellentesque adipiscing commodo elit. Feugiat nibh sed pulvinar proin. Ut sem viverra aliquet eget. Cras fermentum odio eu feugiat pretium nibh ipsum. Duis convallis convallis tellus id interdum velit laoreet id donec. Adipiscing at in tellus integer feugiat. Quam pellentesque nec nam aliquam. Et malesuada fames ac turpis egestas sed. Ac turpis egestas integer eget aliquet nibh. Risus nullam eget felis eget. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique. Sapien eget mi proin sed. Ac auctor augue mauris augue. Tellus at urna condimentum mattis.

                Dolor sed viverra ipsum nunc aliquet bibendum enim. Etiam erat velit scelerisque in dictum non consectetur a erat. Sit amet consectetur adipiscing elit pellentesque. Integer feugiat scelerisque varius morbi enim nunc faucibus a. Risus ultricies tristique nulla aliquet enim. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non. Morbi tristique senectus et netus et malesuada fames ac turpis. Ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Imperdiet sed euismod nisi porta lorem. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Scelerisque varius morbi enim nunc faucibus a pellentesque. Ullamcorper morbi tincidunt ornare massa. Tempor orci dapibus ultrices in iaculis nunc. Viverra nibh cras pulvinar mattis nunc sed blandit libero. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Aliquet eget sit amet tellus cras. Sed euismod nisi porta lorem mollis aliquam ut porttitor.

                Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque sit. Diam donec adipiscing tristique risus. Ut diam quam nulla porttitor. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Nunc non blandit massa enim nec dui nunc mattis enim. Faucibus et molestie ac feugiat sed lectus vestibulum mattis. Placerat duis ultricies lacus sed. Egestas egestas fringilla phasellus faucibus scelerisque eleifend donec pretium. Morbi enim nunc faucibus a pellentesque sit amet porttitor. Malesuada fames ac turpis egestas sed tempus urna et pharetra. Senectus et netus et malesuada fames ac turpis egestas. Viverra accumsan in nisl nisi scelerisque.

                Magna fringilla urna porttitor rhoncus. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Accumsan lacus vel facilisis volutpat est velit egestas. Amet nisl purus in mollis nunc. Faucibus interdum posuere lorem ipsum dolor sit amet consectetur. Aliquet risus feugiat in ante metus. Etiam dignissim diam quis enim lobortis. Mauris vitae ultricies leo integer malesuada nunc vel. Ultrices tincidunt arcu non sodales. Tempus urna et pharetra pharetra massa massa. Sed pulvinar proin gravida hendrerit lectus a. Feugiat pretium nibh ipsum consequat nisl vel. Eu turpis egestas pretium aenean. In hac habitasse platea dictumst quisque sagittis. Vitae elementum curabitur vitae nunc sed velit dignissim sodales.

                Scelerisque mauris pellentesque pulvinar pellentesque. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Vitae ultricies leo integer malesuada nunc vel risus commodo viverra. Pharetra diam sit amet nisl suscipit adipiscing. Hendrerit gravida rutrum quisque non tellus orci. Senectus et netus et malesuada fames ac turpis egestas. Dictumst vestibulum rhoncus est pellentesque. Risus viverra adipiscing at in tellus integer. Nullam eget felis eget nunc lobortis mattis aliquam. Dictumst quisque sagittis purus sit amet volutpat consequat mauris nunc. Adipiscing bibendum est ultricies integer quis auctor. Lacinia at quis risus sed vulputate odio ut enim. Nisl rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Nec sagittis aliquam malesuada bibendum arcu.

                Pulvinar pellentesque habitant morbi tristique senectus et netus et malesuada. Etiam sit amet nisl purus in mollis nunc. Facilisis magna etiam tempor orci eu lobortis. Ridiculus mus mauris vitae ultricies leo.</p>
        </div>
    )
}

export default Home