import {} from 'react'
import './Sobre.css'

function Sobre(){
    return(
        <div className='sobre-container'>
        <img src='https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcRrexBEzpSZzC6VweyZpas3KVdHmk5heWg4oK7mCOpnLRV6RDevlP9l5xNZyqsSQZqNiTJZKulh0ldcCz1zyaF3LCLhLBZxgodZuritl3IcE174uWNPXfIPSg&usqp=CAE' alt='Logo'/>
            <p className='sobre-text'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque adipiscing commodo elit at. Felis bibendum ut tristique et egestas quis ipsum suspendisse. Ultricies integer quis auctor elit sed vulputate mi sit amet. Risus nullam eget felis eget. Diam donec adipiscing tristique risus nec feugiat in fermentum. Et tortor consequat id porta. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. Laoreet suspendisse interdum consectetur libero id faucibus nisl. Facilisi morbi tempus iaculis urna id volutpat. Ornare massa eget egestas purus viverra accumsan in nisl nisi. Vel pretium lectus quam id leo in vitae. Nulla facilisi nullam vehicula ipsum. Ornare aenean euismod elementum nisi quis. Non odio euismod lacinia at quis risus sed vulputate odio. Amet massa vitae tortor condimentum. Tempor nec feugiat nisl pretium fusce id velit ut tortor.

                Tempus quam pellentesque nec nam aliquam sem et tortor consequat. Turpis egestas maecenas pharetra convallis posuere morbi leo urna. Dui ut ornare lectus sit amet est placerat. Quis hendrerit dolor magna eget est lorem ipsum. Et molestie ac feugiat sed lectus vestibulum mattis. Id porta nibh venenatis cras sed. Enim praesent elementum facilisis leo vel fringilla. Ultrices neque ornare aenean euismod elementum. Commodo ullamcorper a lacus vestibulum sed arcu. Sapien et ligula ullamcorper malesuada proin libero. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus et. Felis eget velit aliquet sagittis id consectetur purus ut. Vulputate eu scelerisque felis imperdiet proin fermentum leo vel orci. Ultrices dui sapien eget mi. Sollicitudin ac orci phasellus egestas. Ut faucibus pulvinar elementum integer enim neque volutpat ac. Sagittis aliquam malesuada bibendum arcu vitae. Et netus et malesuada fames ac turpis. In hendrerit gravida rutrum quisque non tellus orci.

                Lorem ipsum dolor sit amet. Massa sapien faucibus et molestie. Ac orci phasellus egestas tellus rutrum. Rhoncus est pellentesque elit ullamcorper dignissim. Vitae suscipit tellus mauris a diam maecenas sed enim. Id diam vel quam elementum pulvinar etiam non quam lacus. Ultrices gravida dictum fusce ut placerat orci nulla pellentesque. Posuere morbi leo urna molestie at elementum eu facilisis. Lorem ipsum dolor sit amet consectetur. Venenatis cras sed felis eget velit aliquet sagittis id. Nulla aliquet porttitor lacus luctus accumsan tortor. Magnis dis parturient montes nascetur ridiculus mus mauris vitae. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Tempus urna et pharetra pharetra massa massa ultricies mi quis. Purus gravida quis blandit turpis cursus. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut placerat. Pellentesque adipiscing commodo elit at imperdiet dui accumsan sit. Lorem ipsum dolor sit amet. Vestibulum sed arcu non odio euismod lacinia at quis risus.

                Vel pretium lectus quam id. Quis commodo odio aenean sed. Aenean sed adipiscing diam donec adipiscing tristique risus. Fermentum leo vel orci porta non pulvinar neque. Porta nibh venenatis cras sed felis eget. Velit dignissim sodales ut eu sem. Vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Integer quis auctor elit sed vulputate mi. Ullamcorper velit sed ullamcorper morbi tincidunt. Sit amet nisl purus in mollis nunc sed id. Bibendum ut tristique et egestas quis ipsum. Diam ut venenatis tellus in. Est sit amet facilisis magna etiam tempor orci eu. Nulla facilisi etiam dignissim diam quis enim lobortis. Tristique senectus et netus et malesuada fames ac turpis egestas.

                Ornare arcu dui vivamus arcu felis bibendum ut. Nisl pretium fusce id velit ut tortor pretium viverra suspendisse. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque eleifend donec. Elementum integer enim neque volutpat ac tincidunt. In dictum non consectetur a erat nam at lectus urna. Convallis posuere morbi leo urna molestie at elementum. Non curabitur gravida arcu ac tortor dignissim convallis aenean et. Neque volutpat ac tincidunt vitae semper quis lectus. Ullamcorper velit sed ullamcorper morbi. In aliquam sem fringilla ut morbi tincidunt augue. Netus et malesuada fames ac turpis egestas maecenas pharetra convallis. Netus et malesuada fames ac. Nisl purus in mollis nunc sed id semper risus in. Amet nisl suscipit adipiscing bibendum est. Tellus cras adipiscing enim eu turpis egestas. Eget nunc lobortis mattis aliquam faucibus purus in massa tempor.

                Ut sem viverra aliquet eget sit amet.</p>
        </div>
    )
}

export default Sobre